"""A project that is ready to render, and nothing more.

The T22 fixture builds a project *plus* a synthetic final render, because T22
inspects a render it did not produce. T17b is the thing that produces it, so its
fixture stops one step earlier: approved script, selected narration with measured
word timings, canonical storyboard timing, locked T15 clips with real media, and
passing T20 video QA - but no render job and no final asset.

The media is generated by FFmpeg at test time from solid colours and a sine
tone. Nothing large or copyrighted is committed.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.orm import Session

from tests.final_qa_fixtures import (
    SHOT_SECONDS,
    _run_passing_video_qa,
    narration_wav,
)
from tests.visual_qa_fixtures import build_visual_qa_project
from vidgen.db.models import RenderJob
from vidgen.db.narration_models import NarrationRun
from vidgen.db.render_models import CaptionTrackRecord
from vidgen.db.storyboard_models import StoryboardShotRecord
from vidgen.storage.asset_service import AssetService
from vidgen.storage.blob import FilesystemBlobStore


@dataclass(slots=True)
class RenderableProject:
    """One project whose authoritative inputs can produce exactly one render."""

    project_id: UUID
    storyboard_run_id: UUID
    narration_run_id: UUID
    narration_asset_id: UUID
    timeline_duration_us: int
    shot_ids: list[UUID] = field(default_factory=list)
    workspace: Path = Path()


def build_renderable_project(
    session: Session,
    blob_root: Path,
    workspace: Path,
    *,
    shot_count: int = 10,
    owner_subject: str = "local-user",
) -> RenderableProject:
    """Build a project that is ready to render and has never been rendered.

    ``shot_count`` must cover every shot in the storyboard: a shot without
    locked media or passing QA is exactly what the executor refuses to render,
    so a partially materialized graph would test the refusal, not the render.
    """
    workspace.mkdir(parents=True, exist_ok=True)
    store = FilesystemBlobStore(blob_root, b"test-secret")
    assets = AssetService(session, store)
    graph = build_visual_qa_project(
        session,
        blob_root,
        workspace / "t20",
        shot_count=shot_count,
        owner_subject=owner_subject,
    )
    _run_passing_video_qa(session, store, graph.project_id)

    shots = list(
        session.scalars(
            select(StoryboardShotRecord)
            .where(StoryboardShotRecord.storyboard_run_id == graph.storyboard_run_id)
            .order_by(StoryboardShotRecord.global_sequence)
        )
    )[:shot_count]
    timeline_us = shots[-1].global_end_us

    narration_path = narration_wav(
        workspace / "narration.wav", segments=len(shots), seconds=SHOT_SECONDS
    )
    narration_asset = assets.store(
        content=narration_path.read_bytes(),
        kind="audio",
        media_type="audio/wav",
        project_id=graph.project_id,
        idempotency_key=f"t12-mix:{graph.project_id}",
    )
    narration_run = session.scalars(
        select(NarrationRun).where(
            NarrationRun.project_id == graph.project_id, NarrationRun.selected.is_(True)
        )
    ).one()
    narration_run.preview_asset_id = narration_asset.id

    # The upstream graph fixture ships a placeholder render row so the review UI
    # has something to project. T17b must start from a project that has never
    # been rendered, so it is removed rather than reused.
    for job in session.scalars(
        select(RenderJob).where(RenderJob.project_id == graph.project_id)
    ).all():
        for track in session.scalars(
            select(CaptionTrackRecord).where(CaptionTrackRecord.render_job_id == job.id)
        ).all():
            session.delete(track)
        session.delete(job)
    session.commit()
    return RenderableProject(
        project_id=graph.project_id,
        storyboard_run_id=graph.storyboard_run_id,
        narration_run_id=narration_run.id,
        narration_asset_id=narration_asset.id,
        timeline_duration_us=timeline_us,
        shot_ids=[shot.id for shot in shots],
        workspace=workspace,
    )
