"""Create the frozen VidGen core relational model.

Revision ID: 0001_core
Revises: None
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001_core"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("target_duration_seconds", sa.Float(), nullable=False),
        sa.Column("visual_style", sa.Text(), nullable=False),
        sa.Column("humor_intensity", sa.Integer(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "humor_intensity BETWEEN 0 AND 10", name=op.f("ck_projects_humor_range")
        ),
        sa.CheckConstraint(
            "target_duration_seconds > 0", name=op.f("ck_projects_positive_target_duration")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(op.f("ix_projects_status"), "projects", ["status"], unique=False)
    op.create_table(
        "assets",
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=128), nullable=True),
        sa.Column("provider_request_id", sa.String(length=255), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("generation_parameters", sa.JSON(), nullable=False),
        sa.Column("extra_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("byte_size >= 0", name=op.f("ck_assets_nonnegative_byte_size")),
        sa.CheckConstraint("length(sha256) = 64", name=op.f("ck_assets_sha256_length")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_assets_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("sha256", name=op.f("uq_assets_sha256")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_assets_storage_key")),
    )
    op.create_index(op.f("ix_assets_idempotency_key"), "assets", ["idempotency_key"], unique=False)
    op.create_index(op.f("ix_assets_kind"), "assets", ["kind"], unique=False)
    op.create_index(op.f("ix_assets_project_id"), "assets", ["project_id"], unique=False)
    op.create_table(
        "plot_beats",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("required_for_coherence", sa.Boolean(), nullable=False),
        sa.Column("scene_ids", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "importance BETWEEN 0 AND 1", name=op.f("ck_plot_beats_importance_range")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_plot_beats_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plot_beats")),
        sa.UniqueConstraint("project_id", "sequence", name=op.f("uq_plot_beats_project_id")),
    )
    op.create_index(op.f("ix_plot_beats_project_id"), "plot_beats", ["project_id"], unique=False)
    op.create_table(
        "scripts",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("contract", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_scripts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scripts")),
        sa.UniqueConstraint("project_id", "revision", name=op.f("uq_scripts_project_id")),
    )
    op.create_index(op.f("ix_scripts_project_id"), "scripts", ["project_id"], unique=False)
    op.create_table(
        "asset_dependencies",
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("parent_asset_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "asset_id <> parent_asset_id", name=op.f("ck_asset_dependencies_not_self_parent")
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_dependencies_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_dependencies_parent_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("asset_id", "parent_asset_id", name=op.f("pk_asset_dependencies")),
    )
    op.create_table(
        "characters",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("bible_asset_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["bible_asset_id"],
            ["assets.id"],
            name=op.f("fk_characters_bible_asset_id_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_characters_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_characters")),
        sa.UniqueConstraint("project_id", "canonical_name", name=op.f("uq_characters_project_id")),
    )
    op.create_index(op.f("ix_characters_project_id"), "characters", ["project_id"], unique=False)
    op.create_table(
        "locations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("reference_asset_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_locations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reference_asset_id"],
            ["assets.id"],
            name=op.f("fk_locations_reference_asset_id_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("project_id", "canonical_name", name=op.f("uq_locations_project_id")),
    )
    op.create_index(op.f("ix_locations_project_id"), "locations", ["project_id"], unique=False)
    op.create_table(
        "render_jobs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("manifest_asset_id", sa.Uuid(), nullable=True),
        sa.Column("output_asset_id", sa.Uuid(), nullable=True),
        sa.Column("error", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["manifest_asset_id"],
            ["assets.id"],
            name=op.f("fk_render_jobs_manifest_asset_id_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["output_asset_id"],
            ["assets.id"],
            name=op.f("fk_render_jobs_output_asset_id_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_render_jobs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_render_jobs")),
    )
    op.create_index(op.f("ix_render_jobs_project_id"), "render_jobs", ["project_id"], unique=False)
    op.create_index(op.f("ix_render_jobs_status"), "render_jobs", ["status"], unique=False)
    op.create_table(
        "script_segments",
        sa.Column("script_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("narration", sa.Text(), nullable=False),
        sa.Column("target_duration_seconds", sa.Float(), nullable=False),
        sa.Column("measured_duration_seconds", sa.Float(), nullable=True),
        sa.Column("contract", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "target_duration_seconds > 0", name=op.f("ck_script_segments_positive_target_duration")
        ),
        sa.ForeignKeyConstraint(
            ["script_id"],
            ["scripts.id"],
            name=op.f("fk_script_segments_script_id_scripts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_script_segments")),
        sa.UniqueConstraint("script_id", "sequence", name=op.f("uq_script_segments_script_id")),
    )
    op.create_index(
        op.f("ix_script_segments_script_id"), "script_segments", ["script_id"], unique=False
    )
    op.create_table(
        "source_videos",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("frame_rate", sa.Float(), nullable=True),
        sa.Column("probe", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_source_videos_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_source_videos_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_videos")),
        sa.UniqueConstraint("asset_id", name=op.f("uq_source_videos_asset_id")),
    )
    op.create_index(
        op.f("ix_source_videos_project_id"), "source_videos", ["project_id"], unique=False
    )
    op.create_table(
        "audio_assets",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("script_segment_id", sa.Uuid(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("provider", sa.String(length=128), nullable=True),
        sa.Column("provider_request_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_audio_assets_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_audio_assets_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["script_segment_id"],
            ["script_segments.id"],
            name=op.f("fk_audio_assets_script_segment_id_script_segments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audio_assets")),
        sa.UniqueConstraint("asset_id", name=op.f("uq_audio_assets_asset_id")),
    )
    op.create_index(
        op.f("ix_audio_assets_project_id"), "audio_assets", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_audio_assets_script_segment_id"),
        "audio_assets",
        ["script_segment_id"],
        unique=False,
    )
    op.create_table(
        "scenes",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("source_start_seconds", sa.Float(), nullable=False),
        sa.Column("source_end_seconds", sa.Float(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("analysis", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source_end_seconds > source_start_seconds", name=op.f("ck_scenes_valid_time_range")
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_scenes_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_scenes_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenes")),
        sa.UniqueConstraint("project_id", "sequence", name=op.f("uq_scenes_project_id")),
    )
    op.create_index(op.f("ix_scenes_project_id"), "scenes", ["project_id"], unique=False)
    op.create_table(
        "shots",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("script_segment_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("contract", sa.JSON(), nullable=False),
        sa.Column("selected_image_id", sa.Uuid(), nullable=True),
        sa.Column("selected_video_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("duration_seconds > 0", name=op.f("ck_shots_positive_duration")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_shots_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["script_segment_id"],
            ["script_segments.id"],
            name=op.f("fk_shots_script_segment_id_script_segments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["selected_image_id"],
            ["generated_images.id"],
            name="fk_shots_selected_image_id_generated_images",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["selected_video_id"],
            ["generated_videos.id"],
            name="fk_shots_selected_video_id_generated_videos",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shots")),
        sa.UniqueConstraint("project_id", "sequence", name=op.f("uq_shots_project_id")),
    )
    op.create_index(op.f("ix_shots_project_id"), "shots", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_shots_script_segment_id"), "shots", ["script_segment_id"], unique=False
    )
    op.create_index(
        "ix_shots_selected_image",
        "shots",
        ["selected_image_id"],
        unique=False,
        postgresql_where=sa.text("selected_image_id IS NOT NULL"),
        sqlite_where=sa.text("selected_image_id IS NOT NULL"),
    )
    op.create_index(
        "ix_shots_selected_video",
        "shots",
        ["selected_video_id"],
        unique=False,
        postgresql_where=sa.text("selected_video_id IS NOT NULL"),
        sqlite_where=sa.text("selected_video_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_shots_status"), "shots", ["status"], unique=False)
    op.create_table(
        "generated_images",
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=128), nullable=False),
        sa.Column("provider_request_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_generated_images_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shot_id"],
            ["shots.id"],
            name=op.f("fk_generated_images_shot_id_shots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_images")),
        sa.UniqueConstraint("asset_id", name=op.f("uq_generated_images_asset_id")),
        sa.UniqueConstraint("shot_id", "attempt", name=op.f("uq_generated_images_shot_id")),
    )
    op.create_index(
        op.f("ix_generated_images_shot_id"), "generated_images", ["shot_id"], unique=False
    )
    op.create_table(
        "qa_results",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("overall_score BETWEEN 0 AND 1", name=op.f("ck_qa_results_score_range")),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_qa_results_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_qa_results_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shot_id"], ["shots.id"], name=op.f("fk_qa_results_shot_id_shots"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qa_results")),
    )
    op.create_index(op.f("ix_qa_results_asset_id"), "qa_results", ["asset_id"], unique=False)
    op.create_index(op.f("ix_qa_results_decision"), "qa_results", ["decision"], unique=False)
    op.create_index(op.f("ix_qa_results_project_id"), "qa_results", ["project_id"], unique=False)
    op.create_index(op.f("ix_qa_results_shot_id"), "qa_results", ["shot_id"], unique=False)
    op.create_table(
        "generated_videos",
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("source_image_id", sa.Uuid(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=False),
        sa.Column("provider", sa.String(length=128), nullable=False),
        sa.Column("provider_request_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_generated_videos_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shot_id"],
            ["shots.id"],
            name=op.f("fk_generated_videos_shot_id_shots"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_image_id"],
            ["generated_images.id"],
            name=op.f("fk_generated_videos_source_image_id_generated_images"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_videos")),
        sa.UniqueConstraint("asset_id", name=op.f("uq_generated_videos_asset_id")),
        sa.UniqueConstraint("shot_id", "attempt", name=op.f("uq_generated_videos_shot_id")),
    )
    op.create_index(
        op.f("ix_generated_videos_shot_id"), "generated_videos", ["shot_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generated_videos_shot_id"), table_name="generated_videos")
    op.drop_table("generated_videos")
    op.drop_index(op.f("ix_qa_results_shot_id"), table_name="qa_results")
    op.drop_index(op.f("ix_qa_results_project_id"), table_name="qa_results")
    op.drop_index(op.f("ix_qa_results_decision"), table_name="qa_results")
    op.drop_index(op.f("ix_qa_results_asset_id"), table_name="qa_results")
    op.drop_table("qa_results")
    op.drop_index(op.f("ix_generated_images_shot_id"), table_name="generated_images")
    op.drop_table("generated_images")
    op.drop_index(op.f("ix_shots_status"), table_name="shots")
    op.drop_index(
        "ix_shots_selected_video",
        table_name="shots",
        postgresql_where=sa.text("selected_video_id IS NOT NULL"),
        sqlite_where=sa.text("selected_video_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_shots_selected_image",
        table_name="shots",
        postgresql_where=sa.text("selected_image_id IS NOT NULL"),
        sqlite_where=sa.text("selected_image_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_shots_script_segment_id"), table_name="shots")
    op.drop_index(op.f("ix_shots_project_id"), table_name="shots")
    op.drop_table("shots")
    op.drop_index(op.f("ix_scenes_project_id"), table_name="scenes")
    op.drop_table("scenes")
    op.drop_index(op.f("ix_audio_assets_script_segment_id"), table_name="audio_assets")
    op.drop_index(op.f("ix_audio_assets_project_id"), table_name="audio_assets")
    op.drop_table("audio_assets")
    op.drop_index(op.f("ix_source_videos_project_id"), table_name="source_videos")
    op.drop_table("source_videos")
    op.drop_index(op.f("ix_script_segments_script_id"), table_name="script_segments")
    op.drop_table("script_segments")
    op.drop_index(op.f("ix_render_jobs_status"), table_name="render_jobs")
    op.drop_index(op.f("ix_render_jobs_project_id"), table_name="render_jobs")
    op.drop_table("render_jobs")
    op.drop_index(op.f("ix_locations_project_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_characters_project_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_table("asset_dependencies")
    op.drop_index(op.f("ix_scripts_project_id"), table_name="scripts")
    op.drop_table("scripts")
    op.drop_index(op.f("ix_plot_beats_project_id"), table_name="plot_beats")
    op.drop_table("plot_beats")
    op.drop_index(op.f("ix_assets_project_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_kind"), table_name="assets")
    op.drop_index(op.f("ix_assets_idempotency_key"), table_name="assets")
    op.drop_table("assets")
    op.drop_index(op.f("ix_projects_status"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
