"""workflow and evidence persistence

Revision ID: 0005_workflow_evidence
Revises: 0004_subtitle_ingestion
Create Date: 2026-08-26 00:25:57.694829
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005_workflow_evidence"
down_revision: str | None = "0004_subtitle_ingestion"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_workflow_runs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.String(length=255), nullable=False),
        sa.Column("run_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("failure", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_workflow_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_workflow_runs")),
        sa.UniqueConstraint("run_id", name=op.f("uq_project_workflow_runs_run_id")),
        sa.UniqueConstraint("workflow_id", name=op.f("uq_project_workflow_runs_workflow_id")),
    )
    op.create_index(
        "uq_workflow_project_idempotency",
        "project_workflow_runs",
        ["project_id", "idempotency_key"],
        unique=True,
    )
    op.create_table(
        "stage_executions",
        sa.Column("workflow_run_id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("activity_id", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("output_asset_id", sa.Uuid(), nullable=True),
        sa.Column("output_entity_id", sa.Uuid(), nullable=True),
        sa.Column("failure", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_stage_executions_nonnegative_attempt_count")
        ),
        sa.ForeignKeyConstraint(
            ["output_asset_id"],
            ["assets.id"],
            name=op.f("fk_stage_executions_output_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_run_id"],
            ["project_workflow_runs.id"],
            name=op.f("fk_stage_executions_workflow_run_id_project_workflow_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stage_executions")),
    )
    op.create_index(
        "uq_stage_workflow_idempotency",
        "stage_executions",
        ["workflow_run_id", "idempotency_key"],
        unique=True,
    )
    op.create_index(
        "uq_stage_workflow_stage", "stage_executions", ["workflow_run_id", "stage"], unique=True
    )
    op.create_table(
        "evidence_packages",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("source_video_id", sa.Uuid(), nullable=False),
        sa.Column("source_video_asset_id", sa.Uuid(), nullable=False),
        sa.Column("source_audio_asset_id", sa.Uuid(), nullable=True),
        sa.Column("transcript_id", sa.Uuid(), nullable=False),
        sa.Column("transcript_asset_id", sa.Uuid(), nullable=False),
        sa.Column("transcript_origin", sa.String(length=32), nullable=False),
        sa.Column("subtitle_asset_id", sa.Uuid(), nullable=True),
        sa.Column("contact_sheet_asset_id", sa.Uuid(), nullable=True),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(input_hash) = 64", name=op.f("ck_evidence_packages_input_hash_length")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_evidence_packages_positive_version")),
        sa.ForeignKeyConstraint(
            ["contact_sheet_asset_id"],
            ["assets.id"],
            name=op.f("fk_evidence_packages_contact_sheet_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_evidence_packages_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_audio_asset_id"],
            ["assets.id"],
            name=op.f("fk_evidence_packages_source_audio_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_video_asset_id"],
            ["assets.id"],
            name=op.f("fk_evidence_packages_source_video_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_video_id"],
            ["source_videos.id"],
            name=op.f("fk_evidence_packages_source_video_id_source_videos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subtitle_asset_id"],
            ["assets.id"],
            name=op.f("fk_evidence_packages_subtitle_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["transcript_asset_id"],
            ["assets.id"],
            name=op.f("fk_evidence_packages_transcript_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_packages")),
    )
    op.create_index(
        "uq_evidence_project_hash", "evidence_packages", ["project_id", "input_hash"], unique=True
    )
    op.create_index(
        "uq_evidence_project_version", "evidence_packages", ["project_id", "version"], unique=True
    )
    op.create_index(
        "uq_evidence_selected_project",
        "evidence_packages",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("selected"),
        sqlite_where=sa.text("selected = 1"),
    )
    op.create_table(
        "scene_evidence",
        sa.Column("evidence_package_id", sa.Uuid(), nullable=False),
        sa.Column("scene_sequence", sa.Integer(), nullable=False),
        sa.Column("source_start_seconds", sa.Float(), nullable=False),
        sa.Column("source_end_seconds", sa.Float(), nullable=False),
        sa.Column("frame_asset_ids", sa.JSON(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "scene_sequence >= 0", name=op.f("ck_scene_evidence_nonnegative_scene_sequence")
        ),
        sa.CheckConstraint(
            "source_end_seconds > source_start_seconds",
            name=op.f("ck_scene_evidence_valid_source_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_package_id"],
            ["evidence_packages.id"],
            name=op.f("fk_scene_evidence_evidence_package_id_evidence_packages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scene_evidence")),
    )
    op.create_index(
        "uq_scene_evidence_sequence",
        "scene_evidence",
        ["evidence_package_id", "scene_sequence"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_scene_evidence_sequence", table_name="scene_evidence")
    op.drop_table("scene_evidence")
    op.drop_index(
        "uq_evidence_selected_project",
        table_name="evidence_packages",
        postgresql_where=sa.text("selected"),
        sqlite_where=sa.text("selected = 1"),
    )
    op.drop_index("uq_evidence_project_version", table_name="evidence_packages")
    op.drop_index("uq_evidence_project_hash", table_name="evidence_packages")
    op.drop_table("evidence_packages")
    op.drop_index("uq_stage_workflow_stage", table_name="stage_executions")
    op.drop_index("uq_stage_workflow_idempotency", table_name="stage_executions")
    op.drop_table("stage_executions")
    op.drop_index("uq_workflow_project_idempotency", table_name="project_workflow_runs")
    op.drop_table("project_workflow_runs")
    # ### end Alembic commands ###
