"""T23 observability and cost ledger

Revision ID: 0007_observability_costs
Revises: 0006_episode_analysis
Create Date: 2026-08-26 06:00:11.157518
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007_observability_costs"
down_revision: str | None = "0006_episode_analysis"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pricing_versions",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source_metadata", sa.JSON(), nullable=False),
        sa.Column("verification_date", sa.Date(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(currency)=3", name=op.f("ck_pricing_versions_currency_iso")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_versions")),
        sa.UniqueConstraint("name", name=op.f("uq_pricing_versions_name")),
    )
    op.create_table(
        "project_budgets",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("warning_cap", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("hard_cap", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("reserved_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("committed_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("released_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "reserved_amount>=0 AND committed_amount>=0 AND released_amount>=0",
            name=op.f("ck_project_budgets_nonnegative_totals"),
        ),
        sa.CheckConstraint(
            "warning_cap>=0 AND hard_cap>=warning_cap", name=op.f("ck_project_budgets_valid_caps")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_budgets_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_budgets")),
        sa.UniqueConstraint("project_id", name=op.f("uq_project_budgets_project_id")),
    )
    op.create_table(
        "provider_attempts",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("related_entity_type", sa.String(length=64), nullable=True),
        sa.Column("related_entity_id", sa.Uuid(), nullable=True),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("provider_request_id", sa.String(length=255), nullable=True),
        sa.Column("provider_configuration_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("failure_class", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=True),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("actual_cost", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("pricing_version_id", sa.Uuid(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column("span_id", sa.String(length=16), nullable=True),
        sa.Column("temporal_workflow_id", sa.String(length=255), nullable=True),
        sa.Column("temporal_run_id", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("redacted_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("attempt_number>0", name=op.f("ck_provider_attempts_positive_attempt")),
        sa.CheckConstraint(
            "estimated_cost>=0 AND actual_cost>=0",
            name=op.f("ck_provider_attempts_nonnegative_cost"),
        ),
        sa.ForeignKeyConstraint(
            ["pricing_version_id"],
            ["pricing_versions.id"],
            name=op.f("fk_provider_attempts_pricing_version_id_pricing_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_provider_attempts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_attempts")),
        sa.UniqueConstraint(
            "project_id",
            "provider",
            "operation",
            "idempotency_key",
            name=op.f("uq_provider_attempts_project_id"),
        ),
    )
    op.create_index(
        op.f("ix_provider_attempts_project_id"), "provider_attempts", ["project_id"], unique=False
    )
    op.create_index(
        "uq_provider_request_identity",
        "provider_attempts",
        ["provider", "provider_request_id"],
        unique=True,
        postgresql_where=sa.text("provider_request_id IS NOT NULL"),
        sqlite_where=sa.text("provider_request_id IS NOT NULL"),
    )
    op.create_table(
        "provider_price_rates",
        sa.Column("pricing_version_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("usage_unit", sa.String(length=32), nullable=False),
        sa.Column("unit_size", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("effective_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("source_reference", sa.String(length=1024), nullable=False),
        sa.Column("notes", sa.String(length=1024), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "effective_end IS NULL OR effective_end>effective_start",
            name=op.f("ck_provider_price_rates_valid_interval"),
        ),
        sa.CheckConstraint(
            "unit_size>0 AND unit_price>=0", name=op.f("ck_provider_price_rates_nonnegative_rate")
        ),
        sa.ForeignKeyConstraint(
            ["pricing_version_id"],
            ["pricing_versions.id"],
            name=op.f("fk_provider_price_rates_pricing_version_id_pricing_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_price_rates")),
        sa.UniqueConstraint(
            "pricing_version_id",
            "provider",
            "model",
            "operation",
            "usage_unit",
            "effective_start",
            name=op.f("uq_provider_price_rates_pricing_version_id"),
        ),
    )
    op.create_table(
        "cost_reservations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("provider_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("estimated_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("reserved_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "estimated_amount>=0 AND reserved_amount>=0",
            name=op.f("ck_cost_reservations_nonnegative_reservation"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_cost_reservations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_attempt_id"],
            ["provider_attempts.id"],
            name=op.f("fk_cost_reservations_provider_attempt_id_provider_attempts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_reservations")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_cost_reservations_idempotency_key")),
    )
    op.create_table(
        "pipeline_failure_events",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.String(length=255), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("related_entity_type", sa.String(length=64), nullable=True),
        sa.Column("related_entity_id", sa.Uuid(), nullable=True),
        sa.Column("failure_class", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=False),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column("event_version", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("projected_status", sa.String(length=32), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("diagnostics", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["provider_attempts.id"],
            name=op.f("fk_pipeline_failure_events_attempt_id_provider_attempts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_pipeline_failure_events_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_failure_events")),
        sa.UniqueConstraint(
            "idempotency_key", name=op.f("uq_pipeline_failure_events_idempotency_key")
        ),
    )
    op.create_index(
        op.f("ix_pipeline_failure_events_project_id"),
        "pipeline_failure_events",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "cost_ledger_entries",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("provider_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("pricing_version_id", sa.Uuid(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("estimated_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("reserved_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("actual_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("released_amount", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=True),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "estimated_amount>=0 AND reserved_amount>=0 "
            "AND actual_amount>=0 AND released_amount>=0",
            name=op.f("ck_cost_ledger_entries_nonnegative_ledger"),
        ),
        sa.ForeignKeyConstraint(
            ["pricing_version_id"],
            ["pricing_versions.id"],
            name=op.f("fk_cost_ledger_entries_pricing_version_id_pricing_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_cost_ledger_entries_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_attempt_id"],
            ["provider_attempts.id"],
            name=op.f("fk_cost_ledger_entries_provider_attempt_id_provider_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["cost_reservations.id"],
            name=op.f("fk_cost_ledger_entries_reservation_id_cost_reservations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_ledger_entries")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_cost_ledger_entries_idempotency_key")),
    )
    op.create_index(
        op.f("ix_cost_ledger_entries_project_id"),
        "cost_ledger_entries",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cost_ledger_entries_project_id"), table_name="cost_ledger_entries")
    op.drop_table("cost_ledger_entries")
    op.drop_index(
        op.f("ix_pipeline_failure_events_project_id"), table_name="pipeline_failure_events"
    )
    op.drop_table("pipeline_failure_events")
    op.drop_table("cost_reservations")
    op.drop_table("provider_price_rates")
    op.drop_index(
        "uq_provider_request_identity",
        table_name="provider_attempts",
        postgresql_where=sa.text("provider_request_id IS NOT NULL"),
        sqlite_where=sa.text("provider_request_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_provider_attempts_project_id"), table_name="provider_attempts")
    op.drop_table("provider_attempts")
    op.drop_table("project_budgets")
    op.drop_table("pricing_versions")
    # ### end Alembic commands ###
