"""image generation

Revision ID: 0011_image_generation
Revises: 0010_storyboard
Create Date: 2026-08-27 00:23:09.732673
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011_image_generation"
down_revision: str | None = "0010_storyboard"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_generation_runs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("storyboard_id", sa.Uuid(), nullable=False),
        sa.Column("storyboard_version", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provider_configuration_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_compiler_version", sa.String(length=32), nullable=False),
        sa.Column("pipeline_version", sa.String(length=32), nullable=False),
        sa.Column("requested_item_count", sa.Integer(), nullable=False),
        sa.Column("completed_item_count", sa.Integer(), nullable=False),
        sa.Column("failed_item_count", sa.Integer(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(input_hash) = 64", name=op.f("ck_image_generation_runs_image_run_hash_length")
        ),
        sa.CheckConstraint(
            "storyboard_version > 0",
            name=op.f("ck_image_generation_runs_image_run_positive_version"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_image_generation_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["storyboard_id"],
            ["storyboard_runs.id"],
            name=op.f("fk_image_generation_runs_storyboard_id_storyboard_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_generation_runs")),
        sa.UniqueConstraint("project_id", "idempotency_key", name="uq_image_run_idempotency"),
    )
    op.create_index(
        op.f("ix_image_generation_runs_project_id"),
        "image_generation_runs",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "image_generation_items",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("shot_sequence", sa.Integer(), nullable=False),
        sa.Column("keyframe_role", sa.String(length=16), nullable=False),
        sa.Column("generation_identity", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_package", sa.JSON(), nullable=False),
        sa.Column("provider_result", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("selected_generated_image_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "keyframe_role IN ('FIRST_FRAME','LAST_FRAME')",
            name=op.f("ck_image_generation_items_image_item_role"),
        ),
        sa.CheckConstraint(
            "shot_sequence >= 0 AND attempt_count >= 0",
            name=op.f("ck_image_generation_items_image_item_counts"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["image_generation_runs.id"],
            name=op.f("fk_image_generation_items_run_id_image_generation_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shot_id"],
            ["storyboard_shots.id"],
            name=op.f("fk_image_generation_items_shot_id_storyboard_shots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_generation_items")),
        sa.UniqueConstraint(
            "generation_identity", name=op.f("uq_image_generation_items_generation_identity")
        ),
        sa.UniqueConstraint("run_id", "shot_id", "keyframe_role", name="uq_image_item_shot_role"),
    )
    op.create_index(
        op.f("ix_image_generation_items_run_id"), "image_generation_items", ["run_id"], unique=False
    )
    op.create_table(
        "generated_keyframe_images",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("keyframe_role", sa.String(length=16), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("provider_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("reference_hash", sa.String(length=64), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("validation_report", sa.JSON(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "width > 0 AND height > 0 AND byte_size > 0",
            name=op.f("ck_generated_keyframe_images_generated_image_positive_geometry"),
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_generated_keyframe_images_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["image_generation_items.id"],
            name=op.f("fk_generated_keyframe_images_item_id_image_generation_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_generated_keyframe_images_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_attempt_id"],
            ["provider_attempts.id"],
            name=op.f("fk_generated_keyframe_images_provider_attempt_id_provider_attempts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["shot_id"],
            ["storyboard_shots.id"],
            name=op.f("fk_generated_keyframe_images_shot_id_storyboard_shots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_keyframe_images")),
        sa.UniqueConstraint("asset_id", name=op.f("uq_generated_keyframe_images_asset_id")),
        sa.UniqueConstraint("item_id", name=op.f("uq_generated_keyframe_images_item_id")),
    )
    op.create_index(
        op.f("ix_generated_keyframe_images_project_id"),
        "generated_keyframe_images",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "uq_generated_keyframe_selected",
        "generated_keyframe_images",
        ["shot_id", "keyframe_role"],
        unique=True,
        sqlite_where=sa.text("selected = 1"),
        postgresql_where=sa.text("selected"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    for table in (
        "generated_keyframe_images",
        "image_generation_items",
        "image_generation_runs",
    ):
        count = connection.execute(sa.text(f"SELECT COUNT(*) FROM {table}")).scalar_one()
        if count:
            raise RuntimeError(
                "unsafe T14 downgrade refused: image-generation provenance exists; "
                "export or delete generated keyframe records explicitly first"
            )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_generated_keyframe_selected",
        table_name="generated_keyframe_images",
        sqlite_where=sa.text("selected = 1"),
        postgresql_where=sa.text("selected"),
    )
    op.drop_index(
        op.f("ix_generated_keyframe_images_project_id"), table_name="generated_keyframe_images"
    )
    op.drop_table("generated_keyframe_images")
    op.drop_index(op.f("ix_image_generation_items_run_id"), table_name="image_generation_items")
    op.drop_table("image_generation_items")
    op.drop_index(op.f("ix_image_generation_runs_project_id"), table_name="image_generation_runs")
    op.drop_table("image_generation_runs")
    # ### end Alembic commands ###
