"""T15 animation video generation

Revision ID: 0012_animation
Revises: 0011_image_generation
Create Date: 2026-08-27 04:08:55.380378
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012_animation"
down_revision: str | None = "0011_image_generation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animation_runs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("storyboard_id", sa.Uuid(), nullable=False),
        sa.Column("storyboard_version", sa.Integer(), nullable=False),
        sa.Column("image_generation_run_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("routing_policy_version", sa.String(length=64), nullable=False),
        sa.Column("provider_configuration_version", sa.String(length=64), nullable=False),
        sa.Column("pipeline_version", sa.String(length=32), nullable=False),
        sa.Column("requested_item_count", sa.Integer(), nullable=False),
        sa.Column("completed_item_count", sa.Integer(), nullable=False),
        sa.Column("failed_item_count", sa.Integer(), nullable=False),
        sa.Column("original_video_count", sa.Integer(), nullable=False),
        sa.Column("canonical_video_count", sa.Integer(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(input_hash) = 64", name=op.f("ck_animation_runs_animation_run_hash_length")
        ),
        sa.CheckConstraint(
            "requested_item_count >= 0 AND completed_item_count >= 0 "
            "AND failed_item_count >= 0 AND original_video_count >= 0 "
            "AND canonical_video_count >= 0",
            name=op.f("ck_animation_runs_animation_run_nonnegative_counts"),
        ),
        sa.CheckConstraint(
            "storyboard_version > 0", name=op.f("ck_animation_runs_animation_run_positive_version")
        ),
        sa.ForeignKeyConstraint(
            ["image_generation_run_id"],
            ["image_generation_runs.id"],
            name=op.f("fk_animation_runs_image_generation_run_id_image_generation_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_animation_runs_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["storyboard_id"],
            ["storyboard_runs.id"],
            name=op.f("fk_animation_runs_storyboard_id_storyboard_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_animation_runs")),
        sa.UniqueConstraint("project_id", "idempotency_key", name="uq_animation_run_idempotency"),
    )
    op.create_index(
        op.f("ix_animation_runs_project_id"), "animation_runs", ["project_id"], unique=False
    )
    op.create_table(
        "animation_items",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("shot_sequence", sa.Integer(), nullable=False),
        sa.Column("first_keyframe_asset_id", sa.Uuid(), nullable=False),
        sa.Column("last_keyframe_asset_id", sa.Uuid(), nullable=True),
        sa.Column("generation_identity", sa.String(length=64), nullable=False),
        sa.Column("motion_prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("motion_prompt_package", sa.JSON(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=32), nullable=False),
        sa.Column("requested_duration", sa.Float(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("selected_generated_video_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_animation_items_animation_item_attempt_count")
        ),
        sa.CheckConstraint(
            "requested_duration > 0 AND width > 0 AND height > 0",
            name=op.f("ck_animation_items_animation_item_positive_media"),
        ),
        sa.CheckConstraint(
            "shot_sequence >= 0", name=op.f("ck_animation_items_animation_item_sequence")
        ),
        sa.ForeignKeyConstraint(
            ["first_keyframe_asset_id"],
            ["assets.id"],
            name=op.f("fk_animation_items_first_keyframe_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["last_keyframe_asset_id"],
            ["assets.id"],
            name=op.f("fk_animation_items_last_keyframe_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["animation_runs.id"],
            name=op.f("fk_animation_items_run_id_animation_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shot_id"],
            ["storyboard_shots.id"],
            name=op.f("fk_animation_items_shot_id_storyboard_shots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["selected_generated_video_id"],
            ["animation_generated_videos.id"],
            name="fk_animation_items_selected_generated_video",
            ondelete="SET NULL",
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_animation_items")),
        sa.UniqueConstraint(
            "generation_identity", name=op.f("uq_animation_items_generation_identity")
        ),
        sa.UniqueConstraint("run_id", "shot_id", name="uq_animation_item_shot"),
    )
    op.create_index(op.f("ix_animation_items_run_id"), "animation_items", ["run_id"], unique=False)
    op.create_table(
        "animation_generated_videos",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("shot_id", sa.Uuid(), nullable=False),
        sa.Column("animation_item_id", sa.Uuid(), nullable=False),
        sa.Column("provider_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("remote_task_id", sa.String(length=255), nullable=False),
        sa.Column("original_asset_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_asset_id", sa.Uuid(), nullable=False),
        sa.Column("requested_duration", sa.Float(), nullable=False),
        sa.Column("provider_duration", sa.Float(), nullable=False),
        sa.Column("canonical_duration", sa.Float(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("codec", sa.String(length=32), nullable=False),
        sa.Column("container", sa.String(length=32), nullable=False),
        sa.Column("frame_rate", sa.String(length=32), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("validation_report", sa.JSON(), nullable=False),
        sa.Column("trim_manifest", sa.JSON(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(sha256) = 64",
            name=op.f("ck_animation_generated_videos_animation_generated_video_hash_length"),
        ),
        sa.CheckConstraint(
            "requested_duration > 0 AND provider_duration > 0 "
            "AND canonical_duration > 0 AND width > 0 AND height > 0",
            name=op.f("ck_animation_generated_videos_animation_generated_video_positive_media"),
        ),
        sa.ForeignKeyConstraint(
            ["animation_item_id"],
            ["animation_items.id"],
            name=op.f("fk_animation_generated_videos_animation_item_id_animation_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["canonical_asset_id"],
            ["assets.id"],
            name=op.f("fk_animation_generated_videos_canonical_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["original_asset_id"],
            ["assets.id"],
            name=op.f("fk_animation_generated_videos_original_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_animation_generated_videos_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_attempt_id"],
            ["provider_attempts.id"],
            name=op.f("fk_animation_generated_videos_provider_attempt_id_provider_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["shot_id"],
            ["storyboard_shots.id"],
            name=op.f("fk_animation_generated_videos_shot_id_storyboard_shots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_animation_generated_videos")),
        sa.UniqueConstraint(
            "animation_item_id", name=op.f("uq_animation_generated_videos_animation_item_id")
        ),
        sa.UniqueConstraint(
            "canonical_asset_id", name=op.f("uq_animation_generated_videos_canonical_asset_id")
        ),
        sa.UniqueConstraint(
            "original_asset_id", name=op.f("uq_animation_generated_videos_original_asset_id")
        ),
        sa.UniqueConstraint(
            "remote_task_id", name=op.f("uq_animation_generated_videos_remote_task_id")
        ),
    )
    op.create_index(
        op.f("ix_animation_generated_videos_project_id"),
        "animation_generated_videos",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "uq_animation_generated_video_selected",
        "animation_generated_videos",
        ["shot_id"],
        unique=True,
        sqlite_where=sa.text("selected = 1"),
        postgresql_where=sa.text("selected"),
    )
    op.create_table(
        "runway_tasks",
        sa.Column("animation_item_id", sa.Uuid(), nullable=False),
        sa.Column("provider_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("remote_task_id", sa.String(length=255), nullable=True),
        sa.Column("provider_status", sa.String(length=32), nullable=False),
        sa.Column("request_projection", sa.JSON(), nullable=False),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("poll_count", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("failure_message", sa.String(length=1024), nullable=True),
        sa.Column("response_metadata", sa.JSON(), nullable=False),
        sa.Column("cancellation_status", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("poll_count >= 0", name=op.f("ck_runway_tasks_runway_task_poll_count")),
        sa.CheckConstraint(
            "progress IS NULL OR (progress >= 0 AND progress <= 1)",
            name=op.f("ck_runway_tasks_runway_task_progress"),
        ),
        sa.ForeignKeyConstraint(
            ["animation_item_id"],
            ["animation_items.id"],
            name=op.f("fk_runway_tasks_animation_item_id_animation_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["provider_attempt_id"],
            ["provider_attempts.id"],
            name=op.f("fk_runway_tasks_provider_attempt_id_provider_attempts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runway_tasks")),
        sa.UniqueConstraint(
            "animation_item_id", "provider_attempt_id", name="uq_runway_task_item_attempt"
        ),
        sa.UniqueConstraint(
            "provider_attempt_id", name=op.f("uq_runway_tasks_provider_attempt_id")
        ),
        sa.UniqueConstraint("remote_task_id", name=op.f("uq_runway_tasks_remote_task_id")),
    )
    op.create_index(
        op.f("ix_runway_tasks_animation_item_id"),
        "runway_tasks",
        ["animation_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_runway_tasks_animation_item_id"), table_name="runway_tasks")
    op.drop_table("runway_tasks")
    op.drop_index(
        "uq_animation_generated_video_selected",
        table_name="animation_generated_videos",
        sqlite_where=sa.text("selected = 1"),
        postgresql_where=sa.text("selected"),
    )
    op.drop_index(
        op.f("ix_animation_generated_videos_project_id"), table_name="animation_generated_videos"
    )
    op.drop_table("animation_generated_videos")
    op.drop_index(op.f("ix_animation_items_run_id"), table_name="animation_items")
    op.drop_table("animation_items")
    op.drop_index(op.f("ix_animation_runs_project_id"), table_name="animation_runs")
    op.drop_table("animation_runs")
    # ### end Alembic commands ###
