"""T17 captions and deterministic render persistence

Revision ID: 0013_render
Revises: 0012_animation
Create Date: 2026-08-27 07:31:31.051559
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0013_render"
down_revision: str | None = "0012_animation"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "caption_tracks",
        sa.Column("render_job_id", sa.Uuid(), nullable=False),
        sa.Column("narration_run_id", sa.Uuid(), nullable=False),
        sa.Column("caption_identity", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("cue_count", sa.Integer(), nullable=False),
        sa.Column("start_us", sa.Integer(), nullable=False),
        sa.Column("end_us", sa.Integer(), nullable=False),
        sa.Column("srt_asset_id", sa.Uuid(), nullable=False),
        sa.Column("webvtt_asset_id", sa.Uuid(), nullable=False),
        sa.Column("ass_asset_id", sa.Uuid(), nullable=True),
        sa.Column("validation_report_asset_id", sa.Uuid(), nullable=False),
        sa.Column("configuration_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "cue_count > 0 AND start_us >= 0 AND end_us > start_us",
            name=op.f("ck_caption_tracks_caption_track_valid_range"),
        ),
        sa.CheckConstraint(
            "length(caption_identity) = 64 AND length(configuration_hash) = 64",
            name=op.f("ck_caption_tracks_caption_track_hashes"),
        ),
        sa.CheckConstraint(
            "length(language) BETWEEN 2 AND 16",
            name=op.f("ck_caption_tracks_caption_track_language"),
        ),
        sa.ForeignKeyConstraint(
            ["ass_asset_id"],
            ["assets.id"],
            name=op.f("fk_caption_tracks_ass_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["narration_run_id"],
            ["narration_runs.id"],
            name=op.f("fk_caption_tracks_narration_run_id_narration_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["render_job_id"],
            ["render_jobs.id"],
            name=op.f("fk_caption_tracks_render_job_id_render_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["srt_asset_id"],
            ["assets.id"],
            name=op.f("fk_caption_tracks_srt_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["validation_report_asset_id"],
            ["assets.id"],
            name=op.f("fk_caption_tracks_validation_report_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["webvtt_asset_id"],
            ["assets.id"],
            name=op.f("fk_caption_tracks_webvtt_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_caption_tracks")),
        sa.UniqueConstraint("caption_identity", name=op.f("uq_caption_tracks_caption_identity")),
        sa.UniqueConstraint("render_job_id", name=op.f("uq_caption_tracks_render_job_id")),
    )
    with op.batch_alter_table("caption_tracks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_caption_tracks_narration_run_id"), ["narration_run_id"], unique=False
        )
        batch_op.create_index("ix_caption_tracks_render_job", ["render_job_id"], unique=False)

    op.create_table(
        "render_attempts",
        sa.Column("render_job_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("manifest_hash", sa.String(length=64), nullable=False),
        sa.Column("command_plan_hash", sa.String(length=64), nullable=True),
        sa.Column("operational_metadata", sa.JSON(), nullable=False),
        sa.Column("ffmpeg_version", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_classification", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("diagnostic_asset_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_render_attempts_render_attempt_positive")
        ),
        sa.CheckConstraint(
            "command_plan_hash IS NULL OR length(command_plan_hash) = 64",
            name=op.f("ck_render_attempts_render_attempt_plan_hash"),
        ),
        sa.CheckConstraint(
            "length(manifest_hash) = 64",
            name=op.f("ck_render_attempts_render_attempt_manifest_hash"),
        ),
        sa.ForeignKeyConstraint(
            ["diagnostic_asset_id"],
            ["assets.id"],
            name=op.f("fk_render_attempts_diagnostic_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["render_job_id"],
            ["render_jobs.id"],
            name=op.f("fk_render_attempts_render_job_id_render_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_render_attempts")),
        sa.UniqueConstraint("render_job_id", "attempt_number", name="uq_render_attempt_number"),
    )
    with op.batch_alter_table("render_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_render_attempts_render_job_id"), ["render_job_id"], unique=False
        )

    with op.batch_alter_table("render_jobs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("script_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("script_version", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("narration_run_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("storyboard_run_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("t16_result_reference", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("render_identity", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("idempotency_key", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("input_hash", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("srt_asset_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("webvtt_asset_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("ass_asset_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("premaster_audio_asset_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("final_video_asset_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("verification_report_asset_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("expected_duration_us", sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column("measured_duration_us", sa.BigInteger(), nullable=True))
        batch_op.add_column(
            sa.Column("video_profile", sa.JSON(), nullable=False, server_default="{}")
        )
        batch_op.add_column(
            sa.Column("audio_profile", sa.JSON(), nullable=False, server_default="{}")
        )
        batch_op.add_column(
            sa.Column("caption_profile", sa.JSON(), nullable=False, server_default="{}")
        )
        batch_op.add_column(sa.Column("ffmpeg_version", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column(
                "pipeline_version", sa.String(length=32), nullable=False, server_default="t17/1"
            )
        )
        batch_op.add_column(
            sa.Column("selected", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column("error_code", sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column("started_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(
            "uq_render_jobs_idempotency",
            ["project_id", "idempotency_key"],
            unique=True,
            sqlite_where=sa.text("idempotency_key IS NOT NULL"),
            postgresql_where=sa.text("idempotency_key IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_render_jobs_identity",
            ["render_identity"],
            unique=True,
            sqlite_where=sa.text("render_identity IS NOT NULL"),
            postgresql_where=sa.text("render_identity IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_render_jobs_selected_project",
            ["project_id"],
            unique=True,
            sqlite_where=sa.text("selected = 1"),
            postgresql_where=sa.text("selected"),
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_render_jobs_storyboard_run_id_storyboard_runs"),
            "storyboard_runs",
            ["storyboard_run_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_render_jobs_script_id_scripts"),
            "scripts",
            ["script_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_render_jobs_verification_report_asset_id_assets"),
            "assets",
            ["verification_report_asset_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_render_jobs_ass_asset_id_assets"),
            "assets",
            ["ass_asset_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_render_jobs_narration_run_id_narration_runs"),
            "narration_runs",
            ["narration_run_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_render_jobs_premaster_audio_asset_id_assets"),
            "assets",
            ["premaster_audio_asset_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_render_jobs_final_video_asset_id_assets"),
            "assets",
            ["final_video_asset_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_render_jobs_srt_asset_id_assets"),
            "assets",
            ["srt_asset_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_render_jobs_webvtt_asset_id_assets"),
            "assets",
            ["webvtt_asset_id"],
            ["id"],
            ondelete="RESTRICT",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_render_jobs_render_complete_has_outputs"),
            "status <> 'render_complete' OR (manifest_asset_id IS NOT NULL AND "
            "srt_asset_id IS NOT NULL AND webvtt_asset_id IS NOT NULL AND "
            "final_video_asset_id IS NOT NULL AND "
            "verification_report_asset_id IS NOT NULL)",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_render_jobs_render_expected_duration_positive"),
            "expected_duration_us IS NULL OR expected_duration_us > 0",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_render_jobs_render_identity_hash_length"),
            "render_identity IS NULL OR length(render_identity) = 64",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_render_jobs_render_input_hash_length"),
            "input_hash IS NULL OR length(input_hash) = 64",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_render_jobs_render_measured_duration_positive"),
            "measured_duration_us IS NULL OR measured_duration_us > 0",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("render_jobs", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_render_jobs_render_measured_duration_positive"), type_="check"
        )
        batch_op.drop_constraint(
            batch_op.f("ck_render_jobs_render_input_hash_length"), type_="check"
        )
        batch_op.drop_constraint(
            batch_op.f("ck_render_jobs_render_identity_hash_length"), type_="check"
        )
        batch_op.drop_constraint(
            batch_op.f("ck_render_jobs_render_expected_duration_positive"), type_="check"
        )
        batch_op.drop_constraint(
            batch_op.f("ck_render_jobs_render_complete_has_outputs"), type_="check"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_render_jobs_webvtt_asset_id_assets"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_render_jobs_srt_asset_id_assets"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_render_jobs_final_video_asset_id_assets"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_render_jobs_premaster_audio_asset_id_assets"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_render_jobs_narration_run_id_narration_runs"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_render_jobs_ass_asset_id_assets"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_render_jobs_verification_report_asset_id_assets"), type_="foreignkey"
        )
        batch_op.drop_constraint(batch_op.f("fk_render_jobs_script_id_scripts"), type_="foreignkey")
        batch_op.drop_constraint(
            batch_op.f("fk_render_jobs_storyboard_run_id_storyboard_runs"), type_="foreignkey"
        )
        batch_op.drop_index(
            "uq_render_jobs_selected_project",
            sqlite_where=sa.text("selected = 1"),
            postgresql_where=sa.text("selected"),
        )
        batch_op.drop_index(
            "uq_render_jobs_identity",
            sqlite_where=sa.text("render_identity IS NOT NULL"),
            postgresql_where=sa.text("render_identity IS NOT NULL"),
        )
        batch_op.drop_index(
            "uq_render_jobs_idempotency",
            sqlite_where=sa.text("idempotency_key IS NOT NULL"),
            postgresql_where=sa.text("idempotency_key IS NOT NULL"),
        )
        batch_op.drop_column("completed_at")
        batch_op.drop_column("started_at")
        batch_op.drop_column("error_code")
        batch_op.drop_column("selected")
        batch_op.drop_column("pipeline_version")
        batch_op.drop_column("ffmpeg_version")
        batch_op.drop_column("caption_profile")
        batch_op.drop_column("audio_profile")
        batch_op.drop_column("video_profile")
        batch_op.drop_column("measured_duration_us")
        batch_op.drop_column("expected_duration_us")
        batch_op.drop_column("verification_report_asset_id")
        batch_op.drop_column("final_video_asset_id")
        batch_op.drop_column("premaster_audio_asset_id")
        batch_op.drop_column("ass_asset_id")
        batch_op.drop_column("webvtt_asset_id")
        batch_op.drop_column("srt_asset_id")
        batch_op.drop_column("input_hash")
        batch_op.drop_column("idempotency_key")
        batch_op.drop_column("render_identity")
        batch_op.drop_column("t16_result_reference")
        batch_op.drop_column("storyboard_run_id")
        batch_op.drop_column("narration_run_id")
        batch_op.drop_column("script_version")
        batch_op.drop_column("script_id")

    with op.batch_alter_table("render_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_render_attempts_render_job_id"))

    op.drop_table("render_attempts")
    with op.batch_alter_table("caption_tracks", schema=None) as batch_op:
        batch_op.drop_index("ix_caption_tracks_render_job")
        batch_op.drop_index(batch_op.f("ix_caption_tracks_narration_run_id"))

    op.drop_table("caption_tracks")
    # ### end Alembic commands ###
