"""T18 review UI control plane

Revision ID: 0014_review_ui
Revises: 0013_render
Create Date: 2026-08-27 15:54:36.286809
"""

import os
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0014_review_ui"
down_revision: str | None = "0013_render"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _refuse_destructive_downgrade(connection: sa.Connection) -> None:
    """Refuse to discard recorded approvals unless the operator opts in.

    Downgrading drops ``render_approvals``, which is an audit record of who
    approved which verified render. On an empty table the downgrade is safe and
    proceeds silently.
    """
    approvals = connection.execute(sa.text("SELECT COUNT(*) FROM render_approvals")).scalar_one()
    if approvals and os.getenv("VIDGEN_ALLOW_DESTRUCTIVE_MIGRATION_TEST") != "1":
        raise RuntimeError(
            f"refusing to downgrade 0014_review_ui: {approvals} render approval record(s) "
            "would be destroyed. Export the approvals first, or set "
            "VIDGEN_ALLOW_DESTRUCTIVE_MIGRATION_TEST=1 to proceed."
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_idempotency_records",
        sa.Column("owner_subject", sa.String(length=255), nullable=False),
        sa.Column("operation", sa.String(length=128), nullable=False),
        sa.Column("resource_key", sa.String(length=255), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(request_hash) = 64",
            name=op.f("ck_api_idempotency_records_api_idempotency_hash_length"),
        ),
        sa.CheckConstraint(
            "status_code >= 100 AND status_code < 600",
            name=op.f("ck_api_idempotency_records_api_idempotency_status_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_idempotency_records")),
        sa.UniqueConstraint(
            "owner_subject",
            "operation",
            "resource_key",
            "idempotency_key",
            name="uq_api_idempotency_scope",
        ),
    )
    op.create_table(
        "downstream_invalidations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("origin_type", sa.String(length=64), nullable=False),
        sa.Column("origin_id", sa.Uuid(), nullable=False),
        sa.Column("invalidated_type", sa.String(length=64), nullable=False),
        sa.Column("invalidated_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_downstream_invalidations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_downstream_invalidations")),
    )
    with op.batch_alter_table("downstream_invalidations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_downstream_invalidations_origin",
            ["project_id", "origin_type", "origin_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_downstream_invalidations_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "project_ui_events",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("workflow_id", sa.String(length=255), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "sequence > 0", name=op.f("ck_project_ui_events_project_ui_event_positive_sequence")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_ui_events_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_ui_events")),
        sa.UniqueConstraint("project_id", "sequence", name="uq_project_ui_events_sequence"),
    )
    with op.batch_alter_table("project_ui_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_project_ui_events_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            "ix_project_ui_events_project_sequence", ["project_id", "sequence"], unique=False
        )

    op.create_table(
        "resource_versions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "resource_type IN ("
            "'project','transcript','transcript_segment','script','script_segment',"
            "'storyboard','shot','render')",
            name=op.f("ck_resource_versions_resource_version_known_type"),
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_resource_versions_resource_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_resource_versions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_versions")),
        sa.UniqueConstraint("resource_type", "resource_id", name="uq_resource_versions_identity"),
    )
    with op.batch_alter_table("resource_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resource_versions_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "render_approvals",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("render_job_id", sa.Uuid(), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=False),
        sa.Column("lineage_hash", sa.String(length=64), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(lineage_hash) = 64",
            name=op.f("ck_render_approvals_render_approval_lineage_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_render_approvals_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["render_job_id"],
            ["render_jobs.id"],
            name=op.f("fk_render_approvals_render_job_id_render_jobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_render_approvals")),
        sa.UniqueConstraint(
            "render_job_id", "lineage_hash", name="uq_render_approvals_render_lineage"
        ),
    )
    with op.batch_alter_table("render_approvals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_render_approvals_project_id"), ["project_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _refuse_destructive_downgrade(op.get_bind())
    with op.batch_alter_table("render_approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_render_approvals_project_id"))

    op.drop_table("render_approvals")
    with op.batch_alter_table("resource_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_versions_project_id"))

    op.drop_table("resource_versions")
    with op.batch_alter_table("project_ui_events", schema=None) as batch_op:
        batch_op.drop_index("ix_project_ui_events_project_sequence")
        batch_op.drop_index(batch_op.f("ix_project_ui_events_project_id"))

    op.drop_table("project_ui_events")
    with op.batch_alter_table("downstream_invalidations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_downstream_invalidations_project_id"))
        batch_op.drop_index("ix_downstream_invalidations_origin")

    op.drop_table("downstream_invalidations")
    op.drop_table("api_idempotency_records")
    # ### end Alembic commands ###
