"""Deterministic pre-workflow estimate of video-generation spend per quality mode.

The estimate is arithmetic over the verified pricing registry and the pacing
preset, never a provider call. It tells an owner what economy, balanced and
premium would roughly cost for a recap of the requested length so the choice is
made with a number in view, and it is honest about being a range: shot counts
depend on the narration the script produces, and a bounded share of shots is
regenerated by quality repair.
"""

from __future__ import annotations

from decimal import ROUND_HALF_UP, Decimal
from math import ceil

from services.animation.pricing import PRICING_CONFIGURATION_VERSION, unit_price
from services.animation.providers import (
    GEN4_5_CAPABILITY,
    GEN4_TURBO_CAPABILITY,
    capability_registry_hash,
)
from services.storyboard.pacing import pacing_profile
from vidgen.contracts.generation import (
    GenerationCostEstimate,
    GenerationCostEstimateMode,
    GenerationQuality,
    ShotPacing,
)

#: The share of shots the storyboard typically marks as hero shots. Balanced
#: mode animates only those with Gen-4.5.
DEFAULT_HERO_SHARE = Decimal("0.15")
#: Upper-bound allowance for bounded quality repairs regenerating a shot.
DEFAULT_RETRY_FACTOR = Decimal("1.2")
CENTS = Decimal("0.01")


def _money(value: Decimal) -> str:
    return str(value.quantize(CENTS, rounding=ROUND_HALF_UP))


def estimate_generation_costs(
    *,
    target_duration_seconds: float,
    shot_pacing: ShotPacing,
    hero_share: Decimal = DEFAULT_HERO_SHARE,
    retry_factor: Decimal = DEFAULT_RETRY_FACTOR,
) -> GenerationCostEstimate:
    if target_duration_seconds <= 0:
        raise ValueError("target_duration_seconds must be positive")
    profile = pacing_profile(shot_pacing)
    duration = Decimal(str(target_duration_seconds))
    target_min = Decimal(profile.target_min_us) / 1_000_000
    target_max = Decimal(profile.target_max_us) / 1_000_000
    # Fewer, longer shots at the top of the range; more, shorter ones at the bottom.
    shots_low = max(1, ceil(duration / target_max))
    shots_high = max(1, ceil(duration / target_min))
    # Runway bills whole seconds, so each shot rounds its usable duration up.
    turbo = GEN4_TURBO_CAPABILITY
    seconds_low = shots_low * (turbo.select_duration(float(target_max)) or ceil(target_max))
    seconds_high = shots_high * (turbo.select_duration(float(target_min)) or ceil(target_min))
    seconds_low = max(seconds_low, ceil(duration))
    seconds_high = max(seconds_high, seconds_low)
    turbo_price = unit_price(turbo.model)
    premium_price = unit_price(GEN4_5_CAPABILITY.model)
    blended = (Decimal(1) - hero_share) * turbo_price + hero_share * premium_price

    def cost(price: Decimal, seconds: int, factor: Decimal = Decimal(1)) -> Decimal:
        return price * Decimal(seconds) * factor

    economy_low = cost(turbo_price, seconds_low)
    economy_high = cost(turbo_price, seconds_high, retry_factor)
    balanced_low = cost(blended, seconds_low)
    balanced_high = cost(blended, seconds_high, retry_factor)
    premium_low = cost(premium_price, seconds_low)
    premium_high = cost(premium_price, seconds_high, retry_factor)
    modes = [
        GenerationCostEstimateMode(
            generation_quality=GenerationQuality.ECONOMY,
            primary_model=turbo.model,
            hero_model=turbo.model,
            estimated_low=_money(economy_low),
            estimated_high=_money(economy_high),
            delta_from_economy_low=_money(Decimal(0)),
            delta_from_economy_high=_money(Decimal(0)),
            summary=(
                f"Cheapest. Every shot uses {turbo.display_name} at "
                f"{turbo_price} USD per generated second."
            ),
        ),
        GenerationCostEstimateMode(
            generation_quality=GenerationQuality.BALANCED,
            primary_model=turbo.model,
            hero_model=GEN4_5_CAPABILITY.model,
            estimated_low=_money(balanced_low),
            estimated_high=_money(balanced_high),
            delta_from_economy_low=_money(balanced_low - economy_low),
            delta_from_economy_high=_money(balanced_high - economy_high),
            summary=(
                f"{turbo.display_name} normally; about {int(hero_share * 100)}% of shots "
                f"(hero shots and quality repairs) use {GEN4_5_CAPABILITY.display_name}."
            ),
        ),
        GenerationCostEstimateMode(
            generation_quality=GenerationQuality.PREMIUM,
            primary_model=GEN4_5_CAPABILITY.model,
            hero_model=GEN4_5_CAPABILITY.model,
            estimated_low=_money(premium_low),
            estimated_high=_money(premium_high),
            delta_from_economy_low=_money(premium_low - economy_low),
            delta_from_economy_high=_money(premium_high - economy_high),
            summary=(
                f"Every compatible shot uses {GEN4_5_CAPABILITY.display_name} at "
                f"{premium_price} USD per generated second."
            ),
        ),
    ]
    return GenerationCostEstimate(
        pricing_version=PRICING_CONFIGURATION_VERSION,
        capability_registry_hash=capability_registry_hash(),
        target_duration_seconds=float(duration),
        shot_pacing=shot_pacing,
        estimated_shot_count_low=shots_low,
        estimated_shot_count_high=shots_high,
        generated_seconds_low=seconds_low,
        generated_seconds_high=seconds_high,
        hero_share=str(hero_share),
        retry_factor=str(retry_factor),
        modes=modes,
        notes=[
            "Video generation only; analysis, script, narration, keyframe and QA spend is "
            "the same in every mode.",
            "The low figure assumes no regenerated shots; the high figure allows bounded "
            "quality repairs.",
            "Runway bills whole generated seconds, so every shot rounds up to the next second.",
        ],
    )
