"""Versioned contracts shared by all VidGen pipeline stages."""

from vidgen.contracts.episode import (
    CharacterDefinition,
    CharacterState,
    LocationDefinition,
    SceneDefinition,
)
from vidgen.contracts.episode import (
    PlotBeat as LegacyPlotBeat,
)
from vidgen.contracts.episode_analysis import (
    AliasEvidence,
    AnalysisInference,
    AnalysisObservation,
    AnalysisValidationError,
    AnalysisValidationReport,
    BeatDependency,
    CanonicalScene,
    CharacterCandidate,
    EpisodeAnalysis,
    EpisodeAnalysisResult,
    EpisodeSynthesisRequest,
    LocationCandidate,
    PlotBeat,
    ProviderEpisodeAnalysisResult,
    ProviderMetadata,
    ProviderSceneAnalysisResult,
    Relationship,
    SceneAnalysisRequest,
    SceneAnalysisResult,
    SceneEvidenceExcerpt,
    SourceReference,
    StateEvent,
    StructuredNote,
    UnresolvedAmbiguity,
)
from vidgen.contracts.evidence import (
    EvidenceDiagnostic,
    EvidencePackage,
    EvidenceProvenance,
    EvidenceTranscriptItem,
    SceneEvidence,
    SourceTimeRange,
)
from vidgen.contracts.media import (
    AudioExtractionResult,
    ExtractedFrame,
    MediaProbeResult,
    MediaProcessingResult,
    SceneDetectionResult,
)
from vidgen.contracts.qa import QAResult
from vidgen.contracts.script import RecapScript, ScriptSegment
from vidgen.contracts.storyboard import ShotDefinition, Storyboard
from vidgen.contracts.subtitles import (
    CanonicalSubtitleTranscriptArtifact,
    ProviderSubtitleDownload,
    SubtitleCandidate,
    SubtitleCue,
    SubtitleImportResult,
    SubtitleQuality,
    SubtitleSearchRequest,
)
from vidgen.contracts.transcription import (
    AudioChunk,
    CanonicalTranscriptArtifact,
    ChunkTranscriptionResult,
    DiarizationRequest,
    DiarizationResult,
    SpeakerTurn,
    TimeInterval,
    TranscriptCoverage,
    TranscriptionRequest,
    TranscriptionResult,
    TranscriptionWarning,
    TranscriptSegment,
    TranscriptWord,
)
from vidgen.contracts.workflow import (
    ProjectWorkflowInput,
    ProjectWorkflowState,
    StageActivityInput,
    StageActivityResult,
    WorkflowFailure,
)

__all__ = [
    "AliasEvidence",
    "AnalysisInference",
    "AnalysisObservation",
    "AnalysisValidationError",
    "AnalysisValidationReport",
    "AudioChunk",
    "AudioExtractionResult",
    "BeatDependency",
    "CanonicalScene",
    "CanonicalSubtitleTranscriptArtifact",
    "CanonicalTranscriptArtifact",
    "CharacterCandidate",
    "CharacterDefinition",
    "CharacterState",
    "ChunkTranscriptionResult",
    "DiarizationRequest",
    "DiarizationResult",
    "EpisodeAnalysis",
    "EpisodeAnalysisResult",
    "EpisodeSynthesisRequest",
    "EvidenceDiagnostic",
    "EvidencePackage",
    "EvidenceProvenance",
    "EvidenceTranscriptItem",
    "ExtractedFrame",
    "LegacyPlotBeat",
    "LocationCandidate",
    "LocationDefinition",
    "MediaProbeResult",
    "MediaProcessingResult",
    "PlotBeat",
    "ProjectWorkflowInput",
    "ProjectWorkflowState",
    "ProviderEpisodeAnalysisResult",
    "ProviderMetadata",
    "ProviderSceneAnalysisResult",
    "ProviderSubtitleDownload",
    "QAResult",
    "RecapScript",
    "Relationship",
    "SceneAnalysisRequest",
    "SceneAnalysisResult",
    "SceneDefinition",
    "SceneDetectionResult",
    "SceneEvidence",
    "SceneEvidenceExcerpt",
    "ScriptSegment",
    "ShotDefinition",
    "SourceReference",
    "SourceTimeRange",
    "SpeakerTurn",
    "StageActivityInput",
    "StageActivityResult",
    "StateEvent",
    "Storyboard",
    "StructuredNote",
    "SubtitleCandidate",
    "SubtitleCue",
    "SubtitleImportResult",
    "SubtitleQuality",
    "SubtitleSearchRequest",
    "TimeInterval",
    "TranscriptCoverage",
    "TranscriptSegment",
    "TranscriptWord",
    "TranscriptionRequest",
    "TranscriptionResult",
    "TranscriptionWarning",
    "UnresolvedAmbiguity",
    "WorkflowFailure",
]
